default: &default
  adapter: postgresql
  encoding: unicode
  host: database
  username: postgres
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: circulation_development

test:
  <<: *default
  database: circulation_test

production:
  <<: *default
  database: circulation_production
  username: circulation
  password: <%= ENV["CIRCULATION_DATABASE_PASSWORD"] %>
